-- users_table creation
create table users_table1(
user_id int primary key,
user_name varchar(100),
gender varchar(100),
city varchar(100),
join_date date
)
select * from users_table1

-- service_table creation
create table service_table1(
service_id int primary key,
service_name varchar(100),
service_type varchar(100),
base_cost decimal(10, 2)
)
select * from service_table1

-- service_usage_table creation
create table service_usage_table1(
usage_id int primary key,
user_id int,
service_id int,
usage_date date,
usage_duration decimal(10, 2),
usage_cost decimal(10, 2)
)
select * from service_usage_table1

-- payment table creation
create table payment1(
payment_id int primary key,
user_id int,
payment_date date,
amount decimal(10, 2),
payment_status varchar(100)
)
select * from payment1

                     -- PHASE 1: BASIC DESCRIPTIVE ANALYSIS --

/* Total Revenue: What is the total revenue generated by the company across all 
services? */

select sum(usage_cost) as total_revenue
from service_usage_table1

/* User Reach: How many unique users are currently registered on the platform? */

select count(distinct user_id) as total_users
from users_table1

/* Service Inventory: What is the total number of unique services offered, and how 
are they distributed across different service types? */

select service_type, count(*) as service_type
from service_table1
group by service_type

/* Usage Volume: What is the total number of service usage transactions recorded 
in the database? */

select count(*) as total_transaction
from service_usage_table1

/* Average Engagement: What is the average duration a user spends using a 
service?  */

select avg(usage_duration) as avg_duration
from service_usage_table1


                       -- PHASE 2: SEGMENTATION & JOINS --

/*  Geographic Performance: Which are the top 5 cities contributing the highest 
revenue? */

select u.city, sum(ur.usage_cost) as city_revenue
from users_table1 u
join service_usage_table1 ur
on u.user_id = ur.user_id
group by city
order by city_revenue desc

/* Category Popularity: Which service_type (e.g., Education, Government, 
Healthcare) has the highest frequency of use? */

select s.service_type, count(ur.usage_id) as service_count
from service_usage_table1 ur
join service_table1 s
on s.service_id = ur.service_id
group by service_type
order by service_count desc

/* Demographic Spending: Is there a significant difference in the average spending 
between Male and Female users? */

select u.gender, ROUND(avg(ur.usage_cost)) as avg_spending
from users_table1 u
join service_usage_table1 ur
on u.user_id = ur.user_id
group by gender

/* Pricing Analysis: What is the average base_cost for services within each service 
category?  */

select service_type, round(avg(base_cost), 2) as average_base_cost
from service_table1
group by service_type
order by average_base_cost desc

/* User Acquisition Trend: How many new users have joined the platform each 
year? */

select extract(year from join_date) as join_year,
count(*) as new_user
from users_table1
group by join_year
order by join_year

/* Peak Activity Period: In which month was the service usage volume at its 
highest? */

select to_char(usage_date, 'month') as peak_month, count(*) as volume
from service_usage_table1
group by peak_month
order by volume desc

                        -- PHASE 3: ADVANCED BUSINESS PROBLEMS --

/* Payment Funnel Analysis: What is the percentage distribution of 'Success', 
'Failed', and 'Pending' payments? */

select payment_status, count(*) as count, 
round(count(*) * 100 / (select count(*) from payment1), 2) as percentage
from payment1
group by payment_status

/* Revenue Leakage: What is the total potential revenue lost due to 'Failed' 
payment transactions? */

select sum(amount) as leaked_revenue
from payment1
where payment_status = 'Failed'

/* Customer Lifetime Value (CLV): Who are the top 10 "Power Users" based on 
their total historical spending? */

select u.user_name, sum(ur.usage_cost) as lifetime_spending
from users_table1 u
join service_usage_table1 ur
on u.user_id = ur.user_id
group by u.user_id, user_name
order by lifetime_spending desc
limit 10

/*  Churn/Retention Analysis: Identify users who have registered but have never 
utilized any service (Inactive Users). */

select u.user_id, u.user_name, u.city
from users_table1 u
left join service_usage_table1 ur
on u.user_id = ur.user_id
where ur.usage_id is null
order by user_id asc

/* Month-over-Month (MoM) Growth: What is the monthly revenue trend? Is the 
business showing consistent growth? */

with monthlyrevenue as (
select to_char((usage_date), 'yyyy-mm') as month,
sum(usage_cost) as revenue
from service_usage_table1
group by month
)
select month, revenue, 
lag(revenue) over (order by month) as per_month_revenue,
round(((revenue - lag(revenue) over (order by month)) / lag(revenue)
over(order by month)) * 100, 2) as growth_percentage
from monthlyrevenue

/*  Financial Discrepancy Check: Are there users whose total usage_cost exceeds 
their total successful_payments? (Credit Risk Analysis). */

select u.user_id, u.user_name,
round(sum(ur.total_usage):: numeric, 2) as total_usage_cost,
round(sum(p.total_paid):: numeric, 2) as total_successful_payemnts,
round((sum(ur.total_usage) - sum(p.total_paid)):: numeric, 2) as discrepancy_amount
from users_table1 u
join (
select user_id, sum(usage_cost) as total_usage
from service_usage_table1 
group by user_id) ur
on u.user_id = ur.user_id
join(
select user_id, sum(amount) as total_paid
from payment1
where payment_status = 'Success'
group by user_id
) p
on ur.user_id = p.user_id
where ur.total_usage > p.total_paid
group by u.user_id, u.user_name
order by discrepancy_amount desc
